### ISSUE TITLE
Multiple `required_if` and `required_unless` criteria

### ISSUE THREAD

**Issue by crichardson9** [chantouchsek/validatorjs#306]
I'm exploring how complex it would be to extend both the `required_if` and `required_unless` rules to support multiple criteria.

For example:

```
required_if:field_one,some_value|field_two,some_value
```

This would make the field required if BOTH `field_one` and `field_two` have the specified values.

I've tried to create a custom validation rule, but it is not run unless the field exists in the data.

**Comment by chantouchsek** [comment]
yes, that's great rules. will take time to see it.
