### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by pierredfc** [chantouchsek/validatorjs#412]
Hi,

When importing your library (`import Validator from '@chantouchsek/validatorjs'`) and using `const validation = new Validator(req.body, {name: 'required'});`, i'm getting the following error at runtime :

> C:\Projects\stack\node_modules\@chantouchsek\validatorjs\dist\main.js:1
> import { get, isArray } from 'lodash';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at internalCompileFunction (node:internal/vm:74:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1141:20)
>     at Module._compile (node:internal/modules/cjs/loader:1182:27)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
>     at Module.load (node:internal/modules/cjs/loader:1081:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:922:12)
>     at Function.Module._load (C:\Projects\stack\packages\js\src\executors\node\node-with-require-overrides.ts:16:27)
>     at Module.require (node:internal/modules/cjs/loader:1105:19)
>     at require (node:internal/modules/cjs/helpers:103:18)
>     at Object.@chantouchsek/validatorjs (C:\Projects\stack\dist\apps\admin-api\webpack:\photo-box\external commonjs "@chantouchsek\validatorjs":1:1)

I'm using node 18.13 and Typescript. Can we really use it with TS ?

**Comment by RomainDECOSTER** [comment]
Hi,

I am also trying to use this lib and I have the same problem.

Regards,

**Comment by chantouchsek** [comment]
let me check it.

**Comment by chantouchsek** [comment]
@pierredfc actually, I am using it with TS, no problems.

**Comment by chantouchsek** [comment]
@pierredfc can you show me your `tsconfig.json`?
`"esModuleInterop": true,` should exist in your config file.

**Comment by pierredfc** [comment]
Hi @chantouchsek, I've added `"esModuleInterop":true` to my tsconfig.base.json but I've got still the error. Below my tsconfig.base.json file :
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2017", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
      ...
    }
  },
  "exclude": ["node_modules", "tmp"]
}
```

**Comment by chantouchsek** [comment]
@pierredfc can you share me the replicate?

**Comment by chantouchsek** [comment]
can you change `"module": "esnext",` => `"module": "es2015",`

**Comment by pierredfc** [comment]
Same error. I'll try to share you a replicate today.

**Comment by chantouchsek** [comment]
Ok, let me know is there anything I can assist.

**Comment by pierredfc** [comment]
Don't succeed to replicate it, i close ! Thanks :)
